// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flowrev-dashboard/CleanPro.tsx": () => import("../components/mockups/flowrev-dashboard/CleanPro.tsx"),
  "./components/mockups/flowrev-dashboard/DarkPro.tsx": () => import("../components/mockups/flowrev-dashboard/DarkPro.tsx"),
  "./components/mockups/flowrev-dashboard/Vibrant.tsx": () => import("../components/mockups/flowrev-dashboard/Vibrant.tsx")
};
